version: '3'
services:
  kissudb:
    image: mysql:5.7
    volumes:
       - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: 

def get_hit_count():
    retries = 5
    while True:
        try:
            return cache.incr('hits')
        except redis.exceptions.ConnectionError as exc:
            if retries == 0:
                raise exc
            retries -= 1
            time.sleep(0.5)

  wordpress:
    image: WordPress:latest
    restart: always
    depends_on:
      - kissudb
    ports:
      - 8809:80
    volumes:
      - wp_storage:/var/www/html/

volumes:
  mysql_storage:
  wp_storage:
