version: '3'
services:
  kissudb:
    image: mysql:5.7
    volumes:
       - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kissu7379
      MYSQL_USER: Kishore
      MYSQL_PASSWORD: redhatkissu
      MYSQL_DATABASE: kissudb


  wordpress:
    image: WordPress:latest
    restart: always
    depends_on:
      - kissudb
    ports:
      - 8809:80
    volumes:
      - wp_storage:/var/www/html/

wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
